# Generated by Django 3.0.8 on 2021-04-23 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('exchange1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange1', to='card.Exchange')),
                ('exchange2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange2', to='card.Exchange')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
