# Generated by Django 3.0.8 on 2021-04-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameKR', models.CharField(default='', max_length=30)),
                ('nameEN', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='exchange1',
        ),
        migrations.RemoveField(
            model_name='card',
            name='exchange2',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='exchanges',
            field=models.ManyToManyField(related_name='exchanges', to='card.Exchange'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='nameEN',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='exchange',
            name='nameKR',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='card',
            name='crypto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto', to='card.Crypto'),
        ),
    ]
