# Generated by Django 3.0.8 on 2021-04-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20210423_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='nameEN',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='nameKR',
        ),
    ]
