# Generated by Django 3.0.8 on 2021-04-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20210423_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_groups',
            field=models.ManyToManyField(related_name='card_groups', to='card.CardGroup'),
        ),
    ]
